const authActionTypes = {
  LOGIN_USER_START: "LOGIN_USER_START",
  GET_CURRENT_USER: "GET_CURRENT_USER",
  LOGOUT_USER: "LOGOUT_USER",
  LOGOUT_FAILED: "LOGOUT_FAILED",
  LOGOUT_START: "LOGOUT_START",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILED: "LOGIN_USER_FAILED",
  CHECK_SESSION: "CHECK_SESSION",
  SIGN_UP_USER_START: "SIGN_UP_USER_START",
  SIGN_UP_USER_SUCCESS: "SIGN_UP_USER_SUCCESS",
  SIGN_UP_USER_FAILED: "SIGN_UP_USER_FAILED",
};

export default authActionTypes;
