const authActionTypes = {
  LOGIN_USER_START: "LOGIN_USER_START",
  GET_CURRENT_USER: "GET_CURRENT_USER",
  LOGOUT_USER: "LOGOUT_USER",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILED: "LOGIN_USER_FAILED",
};

export default authActionTypes;
