const consultantsActionTypes = {
  GET_ALL_CONSULTANTS_START: "GET_ALL_CONSULTANTS_START",
  GET_ALL_CONSULTANTS_SUCCESS: "GET_ALL_CONSULTANTS_SUCCESS",
  GET_ALL_CONSULTANTS_FAILED: "GET_ALL_CONSULTANTS_FAILED",
};

export default consultantsActionTypes;
